kind: pipeline
name: octoprint

platform:
  os: linux
  arch: arm

steps:
  - name: docker
    image: plugins/docker:linux-arm
    settings:
      repo: tinhead/rpi_images
      target: octo
      dockerfile: Dockerfile.armv6
      username:
        from_secret: hub_user
      password:
        from_secret: hub_passwd 
