kind: pipeline
name: octoprint

platform:
  os: linux
  arch: arm

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: tinhead/octoprint
      target: octo
      dockerfile: Dockerfile.armv6
